-- Run this once in the Supabase SQL Editor for the project.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  handle text,
  bio text not null default '',
  avatar_url text,
  interests text[] not null default '{}'::text[]
    check (interests <@ array['GOVERNMENT', 'PARANORMAL', 'TECHNOLOGY', 'HISTORY', 'SPACE']::text[]),
  notification_breaking boolean not null default true,
  notification_comments boolean not null default true,
  notification_weekly boolean not null default false,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint profiles_interests_valid check (
    interests <@ array['GOVERNMENT', 'PARANORMAL', 'TECHNOLOGY', 'HISTORY', 'SPACE']::text[]
  )
);

alter table public.profiles
  add column if not exists interests text[] not null default '{}'::text[],
  add column if not exists notification_breaking boolean not null default true,
  add column if not exists notification_comments boolean not null default true,
  add column if not exists notification_weekly boolean not null default false,
  add column if not exists onboarding_completed boolean not null default false;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'profiles_interests_valid'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_interests_valid check (
        interests <@ array['GOVERNMENT', 'PARANORMAL', 'TECHNOLOGY', 'HISTORY', 'SPACE']::text[]
      );
  end if;
end;
$$;

create unique index if not exists profiles_handle_lower_unique
  on public.profiles (pg_catalog.lower(handle))
  where handle is not null;

create table if not exists public.theories (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles (id) on delete cascade,
  title text not null check (pg_catalog.length(pg_catalog.btrim(title)) > 0),
  excerpt text not null check (pg_catalog.length(pg_catalog.btrim(excerpt)) > 0),
  category text not null check (category in (
    'GOVERNMENT', 'PARANORMAL', 'TECHNOLOGY', 'HISTORY', 'SPACE'
  )),
  image_url text,
  classified boolean not null default false,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now()
);

create index if not exists theories_category_created_idx
  on public.theories (category, created_at desc);
create index if not exists theories_author_created_idx
  on public.theories (author_id, created_at desc);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  theory_id bigint not null references public.theories (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  parent_comment_id bigint,
  text text not null check (pg_catalog.length(pg_catalog.btrim(text)) > 0),
  created_at timestamptz not null default pg_catalog.now(),
  constraint comments_id_theory_unique unique (id, theory_id),
  constraint comments_parent_same_theory_fk
    foreign key (parent_comment_id, theory_id)
    references public.comments (id, theory_id) on delete cascade,
  constraint comments_not_own_parent check (parent_comment_id is null or parent_comment_id <> id)
);

create index if not exists comments_theory_created_idx
  on public.comments (theory_id, created_at);
create index if not exists comments_parent_created_idx
  on public.comments (parent_comment_id, created_at)
  where parent_comment_id is not null;

create table if not exists public.theory_votes (
  theory_id bigint not null references public.theories (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default pg_catalog.now(),
  primary key (theory_id, user_id)
);

create index if not exists theory_votes_user_idx
  on public.theory_votes (user_id, created_at desc);

create table if not exists public.saved_theories (
  theory_id bigint not null references public.theories (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default pg_catalog.now(),
  primary key (theory_id, user_id)
);

create index if not exists saved_theories_user_idx
  on public.saved_theories (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists theories_set_updated_at on public.theories;
create trigger theories_set_updated_at
  before update on public.theories
  for each row execute function public.set_updated_at();

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    nullif(pg_catalog.btrim(new.raw_user_meta_data ->> 'display_name'), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.create_profile_for_new_user();

alter table public.profiles enable row level security;
alter table public.theories enable row level security;
alter table public.comments enable row level security;
alter table public.theory_votes enable row level security;
alter table public.saved_theories enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
  on public.profiles for select to authenticated
  using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert to authenticated
  with check (id = (select auth.uid()));

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

drop policy if exists "Authenticated users can read theories" on public.theories;
create policy "Authenticated users can read theories"
  on public.theories for select to authenticated
  using (true);

drop policy if exists "Users can create their own theories" on public.theories;
create policy "Users can create their own theories"
  on public.theories for insert to authenticated
  with check (author_id = (select auth.uid()));

drop policy if exists "Authors can update their own theories" on public.theories;
create policy "Authors can update their own theories"
  on public.theories for update to authenticated
  using (author_id = (select auth.uid()))
  with check (author_id = (select auth.uid()));

drop policy if exists "Authors can delete their own theories" on public.theories;
create policy "Authors can delete their own theories"
  on public.theories for delete to authenticated
  using (author_id = (select auth.uid()));

drop policy if exists "Authenticated users can read comments" on public.comments;
create policy "Authenticated users can read comments"
  on public.comments for select to authenticated
  using (true);

drop policy if exists "Users can create their own comments" on public.comments;
create policy "Users can create their own comments"
  on public.comments for insert to authenticated
  with check (author_id = (select auth.uid()));

drop policy if exists "Authors can update their own comments" on public.comments;
create policy "Authors can update their own comments"
  on public.comments for update to authenticated
  using (author_id = (select auth.uid()))
  with check (author_id = (select auth.uid()));

drop policy if exists "Authors can delete their own comments" on public.comments;
create policy "Authors can delete their own comments"
  on public.comments for delete to authenticated
  using (author_id = (select auth.uid()));

drop policy if exists "Authenticated users can read theory votes" on public.theory_votes;
create policy "Authenticated users can read theory votes"
  on public.theory_votes for select to authenticated
  using (true);

drop policy if exists "Users can cast their own theory votes" on public.theory_votes;
create policy "Users can cast their own theory votes"
  on public.theory_votes for insert to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists "Users can remove their own theory votes" on public.theory_votes;
create policy "Users can remove their own theory votes"
  on public.theory_votes for delete to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "Users can read their own saved theories" on public.saved_theories;
create policy "Users can read their own saved theories"
  on public.saved_theories for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "Users can save theories for themselves" on public.saved_theories;
create policy "Users can save theories for themselves"
  on public.saved_theories for insert to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists "Users can remove their own saved theories" on public.saved_theories;
create policy "Users can remove their own saved theories"
  on public.saved_theories for delete to authenticated
  using (user_id = (select auth.uid()));

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.theories to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select, insert, delete on public.theory_votes to authenticated;
grant select, insert, delete on public.saved_theories to authenticated;
grant usage, select on sequence public.theories_id_seq, public.comments_id_seq to authenticated;